# Site settings
title: hbtlabs
email: "hassenbentanfous@gmail.com"
description: ""
baseurl: "http://hbtlabs.github.io/"
url: "http://hbtlabs.github.io/"

# Build settings
markdown: kramdown
permalink: pretty
